"""Shared deliverable-collection logic for CLI adapters."""
from __future__ import annotations

import asyncio
import hashlib
import os
import re
import time

ALLOWED_EXTENSIONS = {
    ".xlsx", ".xlsm", ".xls", ".csv", ".tsv", ".docx", ".pdf", ".txt",
    ".md", ".json", ".html", ".png", ".jpg", ".jpeg", ".webp", ".pptx",
}

# A web-development task (see webproject.py) delivers a runnable project,
# not a handful of documents — source files, styles, and config that only
# work as a tree. None of those extensions belong in the document
# allow-list above (a stray `.js` next to a PDF report is scratch work,
# not a deliverable), so they're a separate set switched on only for
# tasks actually identified as web projects.
WEB_EXTENSIONS = {
    ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".css", ".scss", ".sass",
    ".less", ".vue", ".svelte", ".astro", ".svg", ".ico", ".woff", ".woff2",
    ".ttf", ".otf", ".map", ".yml", ".yaml", ".toml", ".env.example", ".gif",
}
WEB_ALLOWED_EXTENSIONS = ALLOWED_EXTENSIONS | WEB_EXTENSIONS
# Extensionless files a real project genuinely needs to run or build.
WEB_ALLOWED_FILENAMES = {
    "dockerfile", "procfile", ".gitignore", ".npmrc", ".nvmrc", ".env.example",
    ".babelrc", ".prettierrc", ".eslintrc",
}
# Never collected from a web project: build output and installed
# dependencies are regenerated by `npm install` / the dev server inside
# the sandbox, and copying them would be enormous and often broken
# (platform-specific binaries).
WEB_IGNORED_DIRS = {
    "node_modules", ".git", ".next", ".nuxt", ".svelte-kit", ".vercel",
    "dist", "build", "out", "coverage", "__pycache__", ".venv", "venv",
    ".cache", ".parcel-cache", ".turbo",
}

MAX_FILE_BYTES = 50 * 1024 * 1024
MAX_FILES = 60
# A real project tree is many small files — a bare Vite+React app is
# already ~10 before any feature code, and the cap has to leave room for
# a genuinely built-out app without also letting a runaway run through.
MAX_WEB_FILES = 400


class DeliverableLimitExceeded(RuntimeError):
    """Raised when a run produced more/larger files than the sane cap —
    treated as a failed run, not a real result (see the two adapters)."""


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def snapshot(workdir: str) -> dict[str, str]:
    """Relative path -> sha256, for every file already in workdir."""
    out: dict[str, str] = {}
    for root, _dirs, files in os.walk(workdir):
        for name in files:
            abspath = os.path.join(root, name)
            relpath = os.path.relpath(abspath, workdir)
            out[relpath] = _sha256(abspath)
    return out


def _normalized_stem(name: str) -> str:
    """Alphanumeric characters only, lowercased — same normalization
    harnesses/ondemand.py's URL matching uses, so a filename that only
    differs by case, dashes vs. underscores, or spacing still counts as
    the same file."""
    stem = os.path.splitext(os.path.basename(name))[0]
    return re.sub(r"[^a-z0-9]", "", stem.lower())


def _web_file_allowed(name: str) -> bool:
    lowered = name.lower()
    if lowered in WEB_ALLOWED_FILENAMES:
        return True
    return os.path.splitext(lowered)[1] in WEB_ALLOWED_EXTENSIONS


def collect_web_project(workdir: str, before: dict[str, str]) -> list[str]:
    """Every file of a generated web project, relative to `workdir`.

    Deliberately NOT filtered by the task's `expected_deliverables`, unlike
    collect_deliverables below: a web project only runs as a whole tree, so
    keeping just the handful of named files would throw away the
    `package.json`, entry point, and styles that make the named files mean
    anything. The scratch-file problem that filter exists to solve doesn't
    apply here either — build output and dependencies are excluded by
    WEB_IGNORED_DIRS instead, which is the actual source of noise in a
    project directory."""
    candidates: list[str] = []
    for root, dirs, files in os.walk(workdir):
        dirs[:] = [d for d in dirs if d.lower() not in WEB_IGNORED_DIRS]
        for name in files:
            abspath = os.path.join(root, name)
            relpath = os.path.relpath(abspath, workdir)
            if not _web_file_allowed(name):
                continue
            try:
                size = os.path.getsize(abspath)
            except OSError:
                continue
            if size > MAX_FILE_BYTES:
                raise DeliverableLimitExceeded(f"deliverable exceeds {MAX_FILE_BYTES} bytes: {relpath}")
            if before.get(relpath) != _sha256(abspath):
                candidates.append(relpath)
    if len(candidates) > MAX_WEB_FILES:
        raise DeliverableLimitExceeded(
            f"agent produced {len(candidates)} project files; maximum is {MAX_WEB_FILES}"
        )
    candidates.sort()
    return candidates


def collect_deliverables(workdir: str, before: dict[str, str], expected: list[str] | None = None) -> list[str]:
    """New or changed, allow-listed-extension files, relative to `workdir`,
    sorted for deterministic ordering. Raises DeliverableLimitExceeded if
    the run produced something clearly runaway (a real result never
    plausibly needs this many/large files for these tasks).

    `expected` (the task's own required filenames) restricts the result to
    files that actually match one of them (by normalized stem + same
    extension) — an agent researching a task can easily leave scratch/
    working files behind in the workdir (one JSON per source it looked at,
    a notes file, ...) that are genuinely new/changed and would otherwise
    get collected right alongside the real deliverable, or even mistaken
    for it. Matched against the RAW candidate count for the runaway check
    below (a flood of junk files is still a flood, whether or not any of
    it happens to match); the filter itself only narrows what's actually
    returned. Omit `expected` (or pass an empty list) to keep the old
    unfiltered behavior — every current call site always has a real
    expected list, so this is only a fallback for a caller that doesn't."""
    candidates: list[str] = []
    for root, _dirs, files in os.walk(workdir):
        for name in files:
            abspath = os.path.join(root, name)
            relpath = os.path.relpath(abspath, workdir)
            if os.path.splitext(name)[1].lower() not in ALLOWED_EXTENSIONS:
                continue
            size = os.path.getsize(abspath)
            if size > MAX_FILE_BYTES:
                raise DeliverableLimitExceeded(f"deliverable exceeds {MAX_FILE_BYTES} bytes: {relpath}")
            if before.get(relpath) != _sha256(abspath):
                candidates.append(relpath)
    if len(candidates) > MAX_FILES:
        raise DeliverableLimitExceeded(f"agent produced {len(candidates)} deliverable files; maximum is {MAX_FILES}")
    if expected:
        wanted = {(_normalized_stem(name), os.path.splitext(name)[1].lower()) for name in expected}
        candidates = [
            c for c in candidates if (_normalized_stem(c), os.path.splitext(c)[1].lower()) in wanted
        ]
    candidates.sort()
    return candidates


def deliverable_activity(workdir: str, before: dict[str, str]) -> dict[str, tuple[int, int]]:
    """A cheap signature for new/changed real deliverables currently on disk.

    This deliberately avoids hashing files while an agent might still be
    writing them. An activity event is enough to extend the inactivity
    deadline; final collection remains hash-based after the CLI exits.
    """
    activity: dict[str, tuple[int, int]] = {}
    for root, _dirs, files in os.walk(workdir):
        for name in files:
            if os.path.splitext(name)[1].lower() not in ALLOWED_EXTENSIONS:
                continue
            abspath = os.path.join(root, name)
            relpath = os.path.relpath(abspath, workdir)
            try:
                stat = os.stat(abspath)
            except FileNotFoundError:
                continue  # Agent replaced the file between walk and stat.
            # Empty placeholders are not a deliverable yet, so they must not
            # keep an otherwise stalled process alive indefinitely.
            if stat.st_size <= 0:
                continue
            if relpath not in before or before.get(relpath) != _sha256(abspath):
                activity[relpath] = (stat.st_size, stat.st_mtime_ns)
    return activity


def expected_deliverables_ready(workdir: str, expected: list[str]) -> bool:
    """Whether every required deliverable exists and has non-empty content.

    Expected filenames come from the dataset and are rendered into the agent
    prompt as files to create directly in the workdir.  Do not treat helper
    files (such as the Internet API schema) as task completion.
    """
    if not expected:
        return False
    for relpath in expected:
        abspath = os.path.abspath(os.path.join(workdir, relpath))
        if os.path.commonpath((workdir, abspath)) != os.path.abspath(workdir):
            return False
        if not os.path.isfile(abspath) or os.path.getsize(abspath) <= 0:
            return False
    return True


async def communicate_with_deliverable_timeout(
    proc, prompt: str, workdir: str, before: dict[str, str], timeout: float, expected: list[str] | None = None
):
    """Run a CLI until it exits, completes every expected file, or stalls.

    Every new or modified allowed deliverable resets the full timeout window.
    The initial window starts when the process begins, so a task that never
    creates a file still has a bounded runtime.  Once every expected filename
    is present and non-empty, stop the CLI and return its files immediately;
    further agent refinement is not part of producing the requested result.
    """
    async def _finish_communicate() -> tuple[bytes, bytes]:
        # A process that exits (or is killed) while communicate()'s own
        # stdin-write coroutine is still mid-flight is a real race: on some
        # event loops (uvloop observed in practice) that raises instead of
        # the BrokenPipeError stdlib asyncio quietly swallows here. Either
        # way the process is already gone — treat it as "no more output to
        # capture" rather than letting it crash the whole run.
        try:
            return await communicate_task
        except (RuntimeError, BrokenPipeError, ConnectionResetError):
            return b"", b""

    communicate_task = asyncio.create_task(proc.communicate(prompt.encode("utf-8")))
    known_activity = deliverable_activity(workdir, before)
    deadline = time.monotonic() + timeout
    while not communicate_task.done():
        if expected_deliverables_ready(workdir, expected or []):
            if proc.returncode is None:
                proc.kill()
            stdout_bytes, stderr_bytes = await _finish_communicate()
            return stdout_bytes, stderr_bytes, False, True
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            if proc.returncode is None:
                proc.kill()
            stdout_bytes, stderr_bytes = await _finish_communicate()
            return stdout_bytes, stderr_bytes, True, False
        try:
            await asyncio.wait_for(asyncio.shield(communicate_task), timeout=min(0.5, remaining))
        except asyncio.TimeoutError:
            current_activity = deliverable_activity(workdir, before)
            if current_activity != known_activity:
                known_activity = current_activity
                deadline = time.monotonic() + timeout
        except (RuntimeError, BrokenPipeError, ConnectionResetError):
            pass
    stdout_bytes, stderr_bytes = await _finish_communicate()
    return stdout_bytes, stderr_bytes, False, False
